# Generated by Django 3.1.7 on 2021-04-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datakolam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datakol',
            options={},
        ),
    ]
